### PR TITLE
update style.css

### PR DESCRIPTION
**Pull request by ogoigbe12**
updated the style.css also made changes to the README.md to make it look more professional also added a folder with the name .github which also has another folder with a name workflow with a file linter.yml

### CODE REVIEW

**Review by AHP15 — CHANGES_REQUESTED** [review]
Hi @ogoigbe12 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
✅ Good job adding `index.html`
✅ Good job adding linter files

## Required Changes ♻️

- [ ] Kindly add `.github` folder in your root directory, and inside of it add another folder with the name `workflows`, and inside of this folder add `linters.yml` file with the content in this [file](https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml), because this will run linter checks when you create a pull request as required in the project requirements
- [ ] Please make sure to follow the Github Flow from the project requirements:
      - All your added files should not be added directly to the `master` branch, but instead to a feature branch (in your case `simple_webpage`)
      - So Kindly remove all of your files from the `master` branch and add them to the `simple_webpage` branch. For more info please check [this](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
 - [ ] Please update your readme file to a professional one because make your repo looks professional and easy to use (because it's well documented), kindly copy this [template](https://github.com/microverseinc/readme-template) from the project requirements, but make sure to CHANGE ITS CONTENT WITH YOU PROJECT CONTENT 😉 
 - [ ] Please make sure to write descriptive commit messages like [those](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
 - [ ] Kindly add a descriptive message to your pull request because it will make it clear what you added in your branch


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @ogoigbe12, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - Good commit messages. ✔️\
 - No lintere errors. ✔️ 
 - Professional README. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] You did a great job building your README file and it looks very professional, but the Pull Request message and title are still not descriptive. The Pull Request should have a descriptive title telling you what changes are inside and should have a short summary describing introduced changes in more detail. As the previous code reviewer asked, please edit them to make it more professional and help the code reviewer understand the purpose of this PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by souad988 — CHANGES_REQUESTED** [review]
Hi @ogoigbe12 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
-while you have done a great work applying changes requested by previous reviewers I'm not able to review your files (html, hintrc and stylelintrc ) and you have a merge conflict that needs to be resolved before getting ready to merge this branch I suggest that you add some small changes to these file in order to get tracked by git and the next reviewer can approve your work 
- Always avoid update , add, edit file x as a PR title or a commit message, instead use meaningful sentences that best describes the feature created in case of a PR or changes done in case of a commit.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by jasonfelice — CHANGES_REQUESTED** [review]
Hi @ogoigbe12,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
- [ ] Please make sure all the linter checks are passing.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AbayomiOlaoye — APPROVED** [review]
Hi @ogoigbe12 :wink: :woman_dancing: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

applause

## Highlights
- Great implementation of reviewer's suggestions :heavy_check_mark: 
- Linter checks are passing :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
